export const FETCH_P_ENTRIES = 'FETCH_P_ENTRIES';
export const FETCH_P_ENTRIES_FULLFILLED = 'FETCH_P_ENTRIES_FULLFILLED';
export const FETCH_P_ENTRIES_REJECTED = 'FETCH_P_ENTRIES_REJECTED';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const UPDATE_ENTRY_REJECTED = 'UPDATE_ENTRY_REJECTED';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_FULLFILLED = 'UPLOAD_IMAGE_FULLFILLED';
export const UPLOAD_IMAGE_REJECTED = 'UPLOAD_IMAGE_REJECTED';
