export const START_LOADING = 'START_LOADING';
export const FETCHING_REJECTED = 'FETCHING_REJECTED';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const UPDATE_START = 'UPDATE_START';
export const UPDATE_REJECTED = 'UPDATE_REJECTED';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_REJECTED = 'UPLOAD_IMAGE_REJECTED';


export const UPDATE = 1;
export const ERROR_UPDATED = -1;
export const NOT_UPDATING = 0;

export const NOT_LOGGING = 0;
export const LOGGED = 1;
export const ERROR_LOGGING = -1;
